import pyautogui
import time

time.sleep(2)
pyautogui.click(300,300)
time.sleep(2)
pyautogui.keyDown('w')
time.sleep(1)
pyautogui.keyDown('w')
time.sleep(2)
pyautogui.keyDown('p')
time.sleep(1.5)
pyautogui.keyDown('a')
time.sleep(3)

pyautogui.keyUp('a')
pyautogui.keyDown('a')
time.sleep(2)
pyautogui.keyUp('a')
pyautogui.keyDown('a')
time.sleep(2)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(2.5)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(1.7)
pyautogui.keyUp('p')
pyautogui.keyUp('a')

time.sleep(2.1)
pyautogui.keyDown('a')
pyautogui.keyDown('p')

time.sleep(1)
pyautogui.keyUp('p')
pyautogui.keyUp('a')
pyautogui.keyDown('p')
pyautogui.keyDown('a')

time.sleep(1.2)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(1.3)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(1.4)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(3.5)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(1.5)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(1.0)
pyautogui.keyUp('a')
pyautogui.keyUp('p')

time.sleep(0.05)
pyautogui.keyDown('p')
pyautogui.keyDown('a')

time.sleep(0.2)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(0.1)
pyautogui.keyUp('p')
time.sleep(0.5)
pyautogui.keyDown('p')
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(2.5)
pyautogui.keyUp('p')
pyautogui.keyDown('o')
time.sleep(2)
pyautogui.keyUp('o')
pyautogui.keyDown('p')
time.sleep(0.5)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(0.5)
pyautogui.keyUp('p')
pyautogui.keyUp('a')
pyautogui.keyDown('a')
pyautogui.keyDown('p')

time.sleep(1.5)
pyautogui.keyUp('p')

time.sleep(1.5)
pyautogui.keyDown('p')
pyautogui.keyUp('a')
pyautogui.keyDown('a')
pyautogui.keyDown('p')

time.sleep(0.5)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(3)
pyautogui.keyUp('p')
pyautogui.keyDown('p')
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(3)
pyautogui.keyUp('p')
pyautogui.keyDown('p')
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(2.5)
pyautogui.keyUp('p')
pyautogui.keyDown('p')
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(2)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(1.0)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(1.1)
pyautogui.keyUp('a')
pyautogui.keyDown('a')

time.sleep(0.5)
pyautogui.keyUp('p')
pyautogui.keyUp('a')
time.sleep(0.1)
pyautogui.keyDown('p')
pyautogui.keyDown('b')
pyautogui.keyDown('a')

time.sleep(2)
pyautogui.keyUp('p')
pyautogui.keyUp('a')
pyautogui.keyDown('p')
time.sleep(0.5)
pyautogui.keyDown('a')

time.sleep(2)
pyautogui.keyUp('p')
pyautogui.keyUp('a')
time.sleep(1)
pyautogui.keyDown('p')
time.sleep(1)
pyautogui.keyDown('a')
